const postTypes = {
	SET_POSTS: 'SET_POSTS',
	SET_POST: 'SET_POST',
	LOAD_SEARCH_SUGGESTION: 'LOAD_SEARCH_SUGGESTION',
	HANDLE_SEARCH_SUGGESTION: 'HANDLE_SEARCH_SUGGESTION',
}

export default postTypes
