const postTypes = {
	APPEND_POSTS: 'APPEND_POSTS',
	SET_LOADING_POSTS: 'SET_LOADING_POSTS',
	SET_LAST_PAGE: 'SET_LAST_PAGE',
	SET_POSTS: 'SET_POSTS',
	SET_ERROR_LOAD_POSTS: 'SET_ERROR_LOAD_POSTS',
	CLEAR_POSTS: 'CLEAR_POSTS',

	SET_POST: 'SET_POST',

	LOAD_SEARCH_SUGGESTION: 'LOAD_SEARCH_SUGGESTION',
	HANDLE_SEARCH_SUGGESTION: 'HANDLE_SEARCH_SUGGESTION',
}

export default postTypes
